version: 2.1

executors:
  my-executor:
    docker:
      - image: node:hydrogen-slim
    working_directory: ~/tmp

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          command: yarn
          name: Install packages
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - run:
          command: ls -a
          name: Current dir
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - ./*
  # deploy:
  #   executor: my-executor
  #   steps:
  #     - attach_workspace:
  #         at: ~/tmp
  #     - run:
  #         command: apt update
  #     - run:
  #         name: Install openssh-client
  #         command: |
  #           apt install openssh-client -y
  #     - run:
  #         name: Deploy app
  #         command: |
  #           scp -r ./packages/server/dist/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR/.

# workflows:
#   version: 2.1
#   build-and-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           # filters:
#           #   branches:
#           #     only: master