version: 2.1

executors:
  my-executor:
    docker:
      - image: node:hydrogen-slim
    working_directory: ~/tmp

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Current dir
          command: ls -a
  deploy:
    executor: my-executor
    steps:
      - run:
          command: apt update
      - run:
          name: Install curl
          command: apt install curl -y
      - run:
          name: Deploy webhook
          command: curl $DEPLOY_WEBHOOK

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
