version: 2.1

executors:
  my-executor:
    docker:
      - image: node:hydrogen-slim
    working_directory: ~/tmp

jobs:
  tests:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn
      - run:
          name: Run tests
          command: yarn test
  deploy-main:
    executor: my-executor
    steps:
      - run:
          command: apt update
      - run:
          name: Install curl
          command: apt install curl -y
      - run:
          name: Deploy webhook
          command: curl $DEPLOY_WEBHOOK
  deploy-test:
    executor: my-executor
    steps:
      - run:
          command: apt update
      - run:
          name: Install curl
          command: apt install curl -y
      - run:
          name: Deploy webhook
          command: curl $DEPLOY_WEBHOOK_TEST

workflows:
  version: 2.1
  tests-and-deploy:
    jobs:
      - tests
      - deploy-main:
          requires:
            - tests
          filters:
            branches:
              only: main
      - deploy-test:
          requires:
            - tests
          filters:
            branches:
              only: test
